---
- name: Import RPM GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Install YUM repo
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgcheck: true
    gpgkey: [https://packages.microsoft.com/keys/microsoft.asc]
    state: present
  become: true

- name: Install
  ansible.builtin.package:
    name: 
      - code
    state: latest
  become: true


