---
- name: Install Development Tools group
  ansible.builtin.package:
    name: '@Development Tools'
    state: latest
  become: true

- name: Set hosts
  ansible.builtin.template:
    dest: /etc/hosts
    src: hosts.j2
  become: true

