---
- name: Import RPM GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install RPM repo
  ansible.builtin.package:
    name: 
      - https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
    state: latest
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install GPG Key (Debian)
  ansible.builtin.shell: >
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
  args:
    creates: /etc/apt/trusted.gpg.d/microsoft.gpg
  become: true
  when: ansible_os_family == 'Debian'

- name: Install Apt Repo (Debian)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main 
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install
  ansible.builtin.package:
    name: 
      - azure-cli
    state: latest
  become: true

