---
- name: Install Kubectl YUM repo (Red Hat)
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install Kubernetes Repo GPG key (Debian)
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  become: true
  when: ansible_os_family == "Debian"

- name: Install Kubernetes Apt Repo (Debian)
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install Kubectl
  ansible.builtin.package:
    name: kubectl
    state: latest
  become: true

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.kube/conf.d"
    state: directory

- name: Copy configs
  copy:
    dest: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_item.key }}.conf"
    content: "{{ kubectl_config_item.value }}"
    mode: 0600
  no_log: true
  loop_control:
    loop_var: kubectl_config_item
  with_items: "{{ kubectl_config | default({}) | dict2items }}"

#- name: Set active
#  ansible.builtin.file:
#    dest: "{{ ansible_user_dir }}/.kube/config"
#    src: "{{ ansible_user_dir }}/.kube/conf.d/{{ kubectl_config_active }}.conf"
#    state: link
#  no_log: true
#  when: kubectl_config[kubectl_config_active] is defined

