---
- name: Install repo
  command:
    cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/hashicorp.repo
  become: true

- name: Install
  ansible.builtin.package:
    name:
      - terraform
    state: latest
  become: true

