---
- name: Install repo
  command:
    cmd: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/gh-cli.repo
  become: true

- name: Install
  ansible.builtin.package:
    name:
      - gh
    state: latest
  become: true

